import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-800`}
      >
        <header className="shadow-sm bg-gray-900">
          <div className="container mx-auto px-4 py-4">
            <h1 className="text-xl font-light text-white">Porsche App</h1>
          </div>
        </header>
        {children}
        <footer className="shadow-sm">
          <div className="container mx-auto px-4 py-4">
            <h2 className="text-xl font-light text-white">Footer</h2>
          </div>
        </footer>
      </body>
    </html>
  );
}